export const clientApi = {
	rows: [
		{
			id: 1,
			client_name: "AMP 1",
			abn: "34 190 894 241",
			org_type: "Government",
			gov_type: "Government",
			state: "New South Wales",
			status: "Active",
		},
		{
			id: 2,
			client_name: "AMP 2",
			abn: "34 190 894 241",
			org_type: "Government",
			gov_type: "Government",
			state: "New South Wales",
			status: "Active",
		},
		{
			id: 3,
			client_name: "AMP 3",
			abn: "34 190 894 241",
			org_type: "Government",
			gov_type: "Government",
			state: "New South Wales",
			status: "Active",
		},
		{
			id: 4,
			client_name: "AMP 4",
			abn: "34 190 894 241",
			org_type: "Government",
			gov_type: "Government",
			state: "New South Wales",
			status: "Active",
		},
		{
			id: 5,
			client_name: "AMP 5",
			abn: "34 190 894 241",
			org_type: "Government",
			gov_type: "Government",
			state: "New South Wales",
			status: "Active",
		},
		{
			id: 6,
			client_name: "AMP 6",
			abn: "34 190 894 241",
			org_type: "Government",
			gov_type: "Government",
			state: "New South Wales",
			status: "Active",
		},
		{
			id: 7,
			client_name: "AMP 7",
			abn: "34 190 894 241",
			org_type: "Government",
			gov_type: "Government",
			state: "New South Wales",
			status: "Active",
		},
		{
			id: 8,
			client_name: "AMP 8",
			abn: "34 190 894 241",
			org_type: "Government",
			gov_type: "Government",
			state: "New South Wales",
			status: "Active",
		},
		{
			id: 9,
			client_name: "AMP 9",
			abn: "34 190 894 241",
			org_type: "Government",
			gov_type: "Government",
			state: "New South Wales",
			status: "Active",
		},
		{
			id: 10,
			client_name: "AMP 10",
			abn: "34 190 894 241",
			org_type: "Government",
			gov_type: "Government",
			state: "New South Wales",
			status: "Active",
		},
	],
	rowCount: 10,
};
