export const taskData = {
	rows: [
		{
			id: 1,
			project: 3897,
			title: "TIMS Upgrade",
			booked: 2,
			task: "Ethics",
		},
		{
			id: 2,
			project: 3898,
			title: "Independent evaluation of Beyond Blue",
			booked: 4.035,
			task: "Meetings",
		},
		{
			id: 3,
			project: 3899,
			title: "TIMS Upgrade 2",
			booked: 1,
			task: "Planning for data collection",
		},
		{
			id: 4,
			project: 3900,
			title: "TIMS Upgrade 3",
			booked: 1,
			task: "Planning for data collection",
		},
	],
	rowCount: 4,
};

export const projectList = {
	rows: [
		{
			id: 1,
			project: 3897,
			title: "The Big Project",
			team: "SLSJ",
			status: "In Progress",
			pd: "AMP",
			pm: "AG",
		},
		{
			id: 2,
			project: 3898,
			title: "The Big Project 2",
			team: "SLSJ",
			status: "In Progress",
			pd: "AMP",
			pm: "AG",
		},
		{
			id: 3,
			project: 3899,
			title: "The Big Project 3",
			team: "SLSJ",
			status: "In Progress",
			pd: "AMP",
			pm: "AG",
		},
		{
			id: 4,
			project: 3400,
			title: "The Big Project 4",
			team: "SLSJ",
			status: "In Progress",
			pd: "AMP",
			pm: "AG",
		},
		{
			id: 5,
			project: 3401,
			title: "The Big Project 5",
			team: "SLSJ",
			status: "In Progress",
			pd: "AMP",
			pm: "AG",
		},
	],
	rowCount: 5,
};

export const proposalApi = {
	rows: [
		{
			id: 1,
			project: 3897,
			classification: "Opportunity",
			title: "The Big Project 1",
			team: "SLSJ",
			status: "In Progress",
			pd: "AMP",
			pm: "AG",
			pr: "BJ",
			dateReceived: "18/03/2022",
			dueDate: "22/03/2022",
		},
		{
			id: 2,
			project: 3897,
			classification: "Opportunity",
			title: "The Big Project 2",
			team: "SLSJ",
			status: "In Progress",
			pd: "AMP",
			pm: "AG",
			pr: "BJ",
			dateReceived: "18/03/2022",
			dueDate: "22/03/2022",
		},
		{
			id: 3,
			project: 3897,
			classification: "Opportunity",
			title: "The Big Project 3",
			team: "SLSJ",
			status: "In Progress",
			pd: "AMP",
			pm: "AG",
			pr: "BJ",
			dateReceived: "18/03/2022",
			dueDate: "22/03/2022",
		},
		{
			id: 4,
			project: 3897,
			classification: "Opportunity",
			title: "The Big Project 4",
			team: "SLSJ",
			status: "In Progress",
			pd: "AMP",
			pm: "AG",
			pr: "BJ",
			dateReceived: "18/03/2022",
			dueDate: "22/03/2022",
		},
		{
			id: 5,
			project: 3897,
			classification: "Opportunity",
			title: "The Big Project 5",
			team: "SLSJ",
			status: "In Progress",
			pd: "AMP",
			pm: "AG",
			pr: "BJ",
			dateReceived: "18/03/2022",
			dueDate: "22/03/2022",
		},
	],
	rowCount: 5,
};

export const ActionApi = {
	rows: [
		{
			id: 1,
			project: 3897,
			title: "Financial Systems Integration",
			toDo: {
				title: "Complete Project Plan",
				status: "warning",
			},
		},
		{
			id: 2,
			project: 3897,
			title: "Financial Systems Integration",
			toDo: {
				title: "Add Team",
				status: "error",
			},
		},
		{
			id: 3,
			project: 3897,
			title: "Add Project Manager",
			toDo: {
				title: "Complete Project Plan",
				status: "warning",
			},
		},
		{
			id: 4,
			project: 3897,
			title: "Financial Systems Integration",
			toDo: {
				title: "No Principal Consultant Selected",
				status: "error",
			},
		},
	],
	rowCount: 5,
};
