export const invoiceApi = {
	rows: [
		{
			id: 1,
			first_name: "Stephanie",
			last_name: "Sanders",
			position: "The Big Project",
			client_name: "AMP 1",
			contact_type: "Reference",
			email: "dan3421@gmail.com",
			status: "Active",
		},
		{
			id: 2,
			first_name: "Stephanie",
			last_name: "Sanders",
			position: "The Big Project",
			client_name: "AMP 2",
			contact_type: "Reference",
			email: "dan3421@gmail.com",
			status: "Active",
		},
		{
			id: 3,
			first_name: "Stephanie",
			last_name: "Sanders",
			position: "The Big Project",
			client_name: "AMP 3",
			contact_type: "Reference",
			email: "dan3421@gmail.com",
			status: "Active",
		},
		{
			id: 4,
			first_name: "Stephanie",
			last_name: "Sanders",
			position: "The Big Project",
			client_name: "AMP 4",
			contact_type: "Reference",
			email: "dan3421@gmail.com",
			status: "Active",
		},
		{
			id: 5,
			first_name: "Stephanie",
			last_name: "Sanders",
			position: "The Big Project",
			client_name: "AMP 5",
			contact_type: "Reference",
			email: "dan3421@gmail.com",
			status: "Active",
		},
		{
			id: 6,
			first_name: "Stephanie",
			last_name: "Sanders",
			position: "The Big Project",
			client_name: "AMP 6",
			contact_type: "Reference",
			email: "dan3421@gmail.com",
			status: "Active",
		},
		{
			id: 7,
			first_name: "Stephanie",
			last_name: "Sanders",
			position: "The Big Project",
			client_name: "AMP 7",
			contact_type: "Reference",
			email: "dan3421@gmail.com",
			status: "Active",
		},
		{
			id: 8,
			first_name: "Stephanie",
			last_name: "Sanders",
			position: "The Big Project",
			client_name: "AMP 8",
			contact_type: "Reference",
			email: "dan3421@gmail.com",
			status: "Active",
		},
		{
			id: 9,
			first_name: "Stephanie",
			last_name: "Sanders",
			position: "The Big Project",
			client_name: "AMP 9",
			contact_type: "Reference",
			email: "dan3421@gmail.com",
			status: "Active",
		},
		{
			id: 10,
			first_name: "Stephanie",
			last_name: "Sanders",
			position: "The Big Project",
			client_name: "AMP 10",
			contact_type: "Reference",
			email: "dan3421@gmail.com",
			status: "Active",
		},
	],
	rowCount: 10,
};
