export const data =
    [
        {
            id: 1,
            isCompleted: true,
            phase: 1,
            task: 23,
            description: 'This is first description.',
            date: new Date(),
            time: new Date(),
            timeXRate: '2,534',
            expenses: '2,534',
            _natc: 1.03,
            _davc: 1.03,
            _jent: 1.03,
            _natc: 1.03,
            _davc: 1.03,
            _jent: 1.03,
        },
        {
            id: 2,
            isCompleted: true,
            phase: 3,
            task: 34,
            description: 'This is second description.',
            date: new Date(),
            time: new Date(),
            timeXRate: '3,434',
            expenses: '3,434',
            _natc: 1.03,
            _davc: 1.03,
            _jent: 1.03,
            _natc: 1.03,
            _davc: 1.03,
            _jent: 1.03,
        },
        {
            id: 3,
            isCompleted: false,
            phase: 54,
            task: 63,
            description: 'This is third description.',
            date: new Date(),
            time: new Date(),
            timeXRate: '7,534',
            expenses: '7,534',
            _natc: 1.03,
            _davc: 1.03,
            _jent: 1.03,
            _natc: 1.03,
            _davc: 1.03,
            _jent: 1.03,
        },
        {
            id: 4,
            isCompleted: false,
            phase: 45,
            task: 67,
            description: 'This is fourth description.',
            date: new Date(),
            time: new Date(),
            timeXRate: '5,434',
            expenses: '5,434',
            _natc: 1.03,
            _davc: 1.03,
            _jent: 1.03,
            _natc: 1.03,
            _davc: 1.03,
            _jent: 1.03,
        },
    ]

